version: '3'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d/
    ports: 
      - "80:80"
    depends_on:
      - web
  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./../../volumes/django_db:/var/lib/postgresql/data
  web:
    build: ./../app
    ports:
      - "8000:8000"
    env_file:
      - ./../app/.env
    command: /app/utils/wait-for-it.sh db:5432 -- bash -c "python manage.py migrate && gunicorn config.wsgi:application --bind 0.0.0.0:8000"
    restart: on-failure
    depends_on:
      - db