version: '3'

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./../../volumes/django_db:/var/lib/postgresql/data
  web:
    build: ./../app
    ports:
      - "8000:8000"
    volumes:
      - ./../app:/app
    env_file:
      - ./../app/.env
    command: /app/utils/wait-for-it.sh db:5432 -- bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db